### ISSUE TITLE
Create Further Visualisations for Current Progress

### ISSUE THREAD

**Issue by sam-mata** [sam-mata/antarctic-ai#78]
### Details
Before the final report can be drafted several visualisations should be created to display progress.

### Checklist
- [ ] Track accuracy and error rates spatially and temporally
- [ ] Visualise interpretability results from #75 
- [ ] Visualise feature importance's from #70 
- [ ] Visualise changes in model architectures *(E.g. with and without bagging, ordering of sequential models)*
- [ ] Visualise training vs evaluation performances *(may require #80)*
